version: "3.7"

networks:
  broadcast-net:
    external: true
  internal:

services:
  queue:
    deploy:
      # labels:
      #   traefik.enable: "true"
      #   traefik.docker.network: broadcast-net
      #   traefik.http.routers.rabbitmq.rule: Host(`dev.xylphid.net`)
      #   traefik.http.routers.rabbitmq.entrypoints: https
      #   traefik.http.routers.rabbitmq.tls: "true"
      #   traefik.http.routers.rabbitmq.tls.certresolver: LE
      #   traefik.http.services.rabbitmq.loadbalancer.server.port: "15672"
      replicas: 1
      restart_policy:
        condition: any
    image: rabbitmq:3.8.5-alpine
    # image: rabbitmq:3.8.5-management-alpine
    networks:
      - broadcast-net
      - internal

  agent:
    command: --mode=agent
    depends_on:
      - queue
    deploy:
      mode: global
      resources:
        limits:
          memory: 50M
      restart_policy:
        condition: any
    environment:
      PYTHONUNBUFFERED: 1
      QUEUE_URL: queue
    image: registry.xylphid.net/swarm-autoscaler:1.0.0
    networks:
      - internal
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock

  orchestrator:
    command: --mode=orchestrator
    depends_on:
      - queue
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      restart_policy:
        condition: any
    environment:
      PYTHONUNBUFFERED: 1
      QUEUE_URL: queue
    image: registry.xylphid.net/swarm-autoscaler:1.0.0
    networks:
      - internal
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock